### ISSUE TITLE
srt to csv too?

### ISSUE THREAD

**Issue by CMMT20** [bryantgtx/csvtosrt#1]
Hi, with this program it is possible convert srt to csv too?
thanks!

**Comment by bryantgtx** [comment]
Wow, sorry about not answering this sooner, I don't recall seeing any notifications come in.  This program was just a quick one-way so I could have a third party fill out a spreadsheet with everything needed for subtitles, no thought at all about going the other way.  Shouldn't be too difficult, though, if anyone wants to do that.
